name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    # Check both runtime and development environments build
    - run: nix-build -A runEnv
    # Execute notebooks and join them into Sphinx docs
    - run: nix-shell -A devEnv --run "make -C doc html"
